### ISSUE TITLE
How to compile? Makefile doesn't work on a pretty standard system.

### ISSUE THREAD

**Issue by glalonde** [emsr/polynomial#9]
Can't find file `../../include/bits/notsospecfun.h`?

**Comment by emsr** [comment]
I need to sort out project inter-dependencies.

**Comment by emsr** [comment]
I fixed dependencies by copying files into this project.
1. Make now should 'work'
2. Make rebuilds everything all the time for some reason.
3. I should do cmake and deprecate make.

**Comment by emsr** [comment]
I put the Jacobi root tester into another make target.
Just plain make should work out of the box again.
